import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://todomvc.com/examples/react/dist/');
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').click();
  await page.getByTestId('text-input').fill('hey 1');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('hey 2');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('hey 3');
  await page.getByTestId('text-input').press('Enter');
  await page.getByTestId('text-input').fill('hey 4');
  await page.getByTestId('text-input').press('Enter');
  await page.getByText('hey 1').click();
  await page.getByRole('listitem').filter({ hasText: 'hey 1' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('listitem').filter({ hasText: 'hey 2' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('button', { name: 'Clear completed' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await expect(page.getByText('hey 4')).toBeVisible();
  await expect(page.getByTestId('todo-list')).toContainText('hey 3');
  await expect(page.getByRole('listitem').filter({ hasText: 'hey 4' }).getByTestId('todo-item-toggle')).not.toBeChecked();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('listitem').filter({ hasText: 'hey 4' }).getByTestId('todo-item-toggle').check();
  await page.getByRole('link', { name: 'Completed' }).click();
  await page.getByRole('link', { name: 'Active' }).click();
  await page.getByRole('link', { name: 'All' }).click();
  await page.getByRole('button', { name: 'Clear completed' }).click();
});